#!/usr/bin/env ruby
# vim: ft=ruby

# from: http://tammersaleh.com/posts/the-modern-vim-config-with-pathogen

git_bundles = [ 
#"git://github.com/astashov/vim-ruby-debugger.git",
  "git://github.com/msanders/snipmate.vim.git",
#"git://github.com/scrooloose/nerdtree.git",
#"git://github.com/timcharper/textile.vim.git",
  "git://github.com/tpope/vim-pathogen.git",
  "git://github.com/tpope/vim-cucumber.git",
  "git://github.com/tpope/vim-fugitive.git",
  "git://github.com/tpope/vim-git.git",
  "git://github.com/tpope/vim-haml.git",
  "git://github.com/tpope/vim-markdown.git",
  "git://github.com/tpope/vim-ragtag.git",
  "git://github.com/tpope/vim-rails.git",
  "git://github.com/tpope/vim-repeat.git",
  "git://github.com/tpope/vim-surround.git",
  "git://github.com/tpope/vim-vividchalk.git",
  "git://github.com/tsaleh/vim-align.git",
  "git://github.com/tsaleh/vim-shoulda.git",
  "git://github.com/tsaleh/vim-supertab.git",
  "git://github.com/tsaleh/vim-tcomment.git",
  "git://github.com/vim-bundles/fuzzyfinder",
#"git://github.com/vim-ruby/vim-ruby.git",
]

vim_org_scripts = [
  ["gist",          "12732", "plugin"],
  ["jquery",        "12107", "syntax"],
  ["file:line",     "9148",  "plugin"],
  ["indexedsearch",     "7062",  "plugin"],
]

require 'fileutils'
require 'open-uri'

FileUtils.cd(bundle_dir = File.expand_path('../bundle/', __FILE__))

git_bundles.each do |url|
  dir = File.basename(url)
  puts "* Unpacking #{url} into #{dir}"
  `cd #{File.join(bundle_dir, dir)} && git pull || git clone #{url} #{dir}`
end

vim_org_scripts.each do |name, script_id, script_type|
  puts "  Downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
end

