#!/usr/bin/env bash

function App() {
	brew cask install "${@}" #2> /dev/null
}

function Brew() {
	brew install "${@}" #2> /dev/null
}

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade

#
# Bash 4
Brew bash
Brew bash-completion
Brew ctags

Brew git
Brew hg

Brew ruby-install
Brew chruby
Brew go

Brew p4merge

Brew wget

Brew homebrew/dupes/grep
Brew rename
Brew pstree
Brew tree
Brew rmtrash

Brew tmux

# Install GNU core utilities (those that come with OS X are outdated)
Brew coreutils
echo "Don’t forget to add $(brew --prefix coreutils)/libexec/gnubin to \$PATH."
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
Brew findutils

Brew imagemagick
Brew rhino
Brew webkit2png

# Install native apps
brew tap phinze/homebrew-cask
brew install brew-cask

App sequel-pro

App slate       # OSS window manager

App dropbox
App google-chrome
App google-chrome-canary
App imagealpha
App imageoptim
App iterm2
App macvim
App miro-video-converter
# App sublime-text
App the-unarchiver
App tor-browser
App transmission
# App ukelele
App virtualbox
App vlc


# Remove outdated versions from the cellar
brew cleanup

xcode-select --install
