#!/usr/bin/env bash

function App() {
	brew cask install "${@}" #2> /dev/null
}

function Brew() {
	brew install "${@}" #2> /dev/null
}

# Make sure we’re using the latest Homebrew
brew update

# Install native apps
brew tap caskroom/cask
# Versions
brew tap homebrew/versions

brew install brew-cask

# Programming
Brew git
Brew hub
Brew hg

Brew ruby-install
Brew chruby
Brew go
Brew socat

App iterm2
App macvim
App sequel-pro
App p4merge
App docker

# CLI
#
# bash4
Brew bash
Brew bash-completion
Brew homebrew/versions/bash-completion2

# Install GNU core utilities (those that come with OS X are outdated)
Brew ctags
Brew coreutils
brew binutils
brew findutils
brew diffutils
brew ed
brew gawk
brew gnu-indent
brew gnu-sed
brew gnu-tar
brew gnu-which
brew gnutls
Brew homebrew/dupes/grep                # GNU grep instead of BSD one
brew gzip
brew watch
brew wdiff
brew wget

Brew pstree
Brew tree

Brew tmux
Brew reattach-to-user-namespace

Brew jq                                 # json tool and formatter
Brew html-xml-utils

Brew rename
Brew mmv                                # mass mv/link/cp/append http://manpages.ubuntu.com/manpages/precise/man1/mmv.1.html
Brew rmtrash                            # aliases rm to delete to OSX's trash

Brew lynx

Brew graphviz
Brew imagemagick
Brew rhino
Brew webkit2png
# Howto video->gif https://gist.github.com/dergachev/4627207
Brew gifsicle

Brew fzf

# GUI
App virtualbox
App Dash                               # Documentation

App Caskroom/cask/tunnelblick

App slate                              # OSX window manager

App google-chrome
App google-chrome-canary

App imagealpha
App imageoptim
App the-unarchiver

App licecap
App keycastr

App miro-video-converter
App vlc

App tor-browser
App transmission

# App dropbox

# Remove outdated versions from the cellar
brew cleanup

# command-line tools
xcode-select --install
