#!/usr/bin/env bash

function App() {
	Brew cask install "${@}" #2> /dev/null
}

function Brew() {
	brew install "${@}" #2> /dev/null
}

# Install native apps
# Brew tap caskroom/cask

# Brew install brew-cask

function Update {
	Brew update
}

function Dev {
	Brew git
	Brew hub
	Brew hg

	Brew socat

	# App iterm2
	App macvim
	
	App sequel-pro
	
	App p4v

	App docker
	
	# command-line tools
	xcode-select --install
}

function Ruby {
	Brew ruby-install
	Brew chruby
}

function Go {
	Brew go
}

function Tools {
	# CLI
	#
	# bash4
	Brew bash
	Brew bash-completion

	# Install GNU core utilities (those that come with OS X are outdated)
	Brew ctags
	Brew coreutils
	Brew binutils
	Brew findutils
	Brew diffutils
	Brew ed
	Brew gawk
	Brew gnu-indent
	Brew gnu-sed
	Brew gnu-tar
	Brew gnu-which
	Brew gnutls
	Brew grep                				# GNU grep instead of BSD one
	Brew gzip
	Brew watch
	Brew wdiff
	Brew wget

	Brew pstree
	Brew tree

	Brew tmux
	Brew reattach-to-user-namespace
	Brew entr                               # fs watcher entrproject.org

	Brew jq                                 # json tool and formatter
	Brew html-xml-utils

	Brew rename
	Brew mmv                                # mass mv/link/cp/append http://manpages.ubuntu.com/manpages/precise/man1/mmv.1.html
	Brew rmtrash                            # aliases rm to delete to OSX's trash

	Brew fzf
}

# Make sure we’re using the latest Homebrew


function Extra {
	Brew lynx

	Brew graphviz
	Brew imagemagick
	Brew rhino
	Brew webkit2png
	# Howto video->gif https://gist.github.com/dergachev/4627207
	Brew gifsicle
}

function Tools_Crypto {
	# EncFS
	App osxfuse
	Brew homebrew/fuse/encfs
}




# # GUI
# # App virtualbox
# App Dash                               # Documentation
# # App Slack

# App visual-studio-code

# App Caskroom/cask/tunnelblick

# App slate                              # OSX window manager

# App google-chrome
# #App google-chrome-canary

# App imagealpha
# App imageoptim
# App the-unarchiver

# App licecap
# App keycastr

# App miro-video-converter
# App vlc

# App tor-browser
# App transmission

# # App dropbox

# # Remove outdated versions from the cellar
# Brew cleanup

function Main {
	for task in "$@"; do
		echo "running $task"
		$task 
	done
}

if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
	echo $@
	Main $@
fi