# .bashrc

source ~/.bash/functions.bash
source ~/.bash/profile
[ "Darwin" == "`uname`" ] &&  source ~/.bash/profile-osx

[[ -s ~/.rubyrc ]] && source ~/.rubyrc

[[ -d ~/bin ]] && export PATH=~/bin:$PATH

[[ -s ~/.rvm/scripts/rvm ]] && source ~/.rvm/scripts/rvm
