#!/bin/sh

# http://gmarik.info/blog/2010/05/02/tracking-dotfiles-with-git 

so() { for f in $@; do [ -s $1 ] && source "$f"; done; }

so ~/.bash/functions                      #
so ~/.bash/colors                         #
so ~/.bash/profile                        # main configuration
so ~/.bash/${ENV_NAME}_profile            # configuration per OS linux/OSX
so ~/.bash/common                         # common stuff or overriding
so ~/.bash/ssh.sh                         # ssh functions
so ~/.bash/prompt.sh                      # PS1 prompt
so ~/.bash/ocaml.sh                       #

so ~/.bash/git                            #
so ~/.bash/dotfilesrc                     # my git-dotfiles specific stuff
so ~/.bash/python                         #
so ~/.bash/node                           # Node stuff.
so ~/.bash/ruby.sh                        #
so ~/.rubyrc                              # Ruby stuff.
so ~/.bash/golang                         # Golang Stuff
so ~/.golangrc                            # Golang Stuff
so ~/.local/*.bash                        # machine specific config. not tracked

[ -d ~/bin ] && export PATH=~/bin:$PATH # users' ~/bin/ takes precedence
[ -d ~/.local/bin ] && export PATH=~/.local/bin:$PATH # untracked local stuff

# vim: ft=sh
