#!/bin/sh
# tpope's http://tbaggery.com/2011/08/08/effortless-ctags-with-git.html

set -e
PATH="/usr/local/bin:$PATH"
trap "rm -f .git/tags.$$" EXIT
ctags --tag-relative -f.git/tags.$$
mv .git/tags.$$ .git/tags

# vim: set ft=sh
