#!/bin/bash

txtred='[0;31m' # Red
txtrst='[0m'     # Reset

user=$(git config --local user.name)
email=$(git config --local user.email)

if [ "${user}" == "" -a "${name}" == "" ]; then
  echo "${txtred}"
  echo "You don't have user/email configured for this repo, please configure!"
  echo "${txtrst}"
  exit 1
fi

