#!/bin/bash

txtred='[0;31m' # Red
txtrst='[0m'     # Reset

user=$(git config --local user.name)
email=$(git config --local user.email)

if [ "${user}" == "" -a "${name}" == "" ]; then
  echo "${txtred}"

  echo "You don't have user/email configured for this repo, please configure!"

  echo "configure with:"
  echo "git config user.email email@address"
  echo "git config user.name 'your full name'"
  echo "${txtrst}"
  exit 1
fi

